instructionsupdated
breatheco-de/exercise-multi-view-react-collaborative-website pull request #1
Opened 2021-03-25 16:25 UTC by ElviraQDP

instrucciones para revision

2021-03-30 15:14 UTC, mortegac requested changes
Falta agregar la versión en español

2021-04-21 18:29 UTC, mortegac requested changes
Revisar comentarios

2021-04-21 18:29 UTC, mortegac commented on README.es.md
> +3. All the students clone the repository.
@ElviraQDP  Puedes dejarlo en español

2021-04-21 18:29 UTC, mortegac commented on README.es.md
> +4. Divide el trabajo del proyecto en partes y cada grupo puede empezar a trabajar en su pieza, 2 o 3 personas máximo por grupo.
Quizás quedaria mejor 
```
divide el proyecto en pequeñas partes para que cada integrante pueda trabajar en ellas.  El grupo debe tener 2 o 3 personas como máximo
```

2021-04-21 19:24 UTC, alesanchezr approved these changes

2021-04-21 19:24 UTC, merged